# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gvrKAaEairg2Q+Byzd3tgaj56cg2B87nnWXef3AF7TxLhiqhpt1LCLCUEYlDEtJDWjdLSRG+N73R2TQIGs1YKR7nk03JpUWnPu2DVGR/CgXBA9awL0bb+5Vu7NKYtlSv6r4iQw5pv8j8rceg6BkrqsuwMQwukHOZnvp265/A8/2Hsz37qx9t2yplW0gKK43JQR0AvW30A/VGc4t2WA+UMyeFRW5dC5lryhN8xcre+NJ5TwMOXiRw3TfLo/1vpOpBtoAoB7rwvN88YlFcm0m1IrMhNoFbuKNaQXUrWVL0lzGvyzF4SglXRvWHVBos8GDE0Ym5iUC19mtvWJ6t8y/ZIKvPSo6VNqhHbt6EFkywjG33IcXnfaGAltInDFIluwfpLgWI9o+kg/PD+Fm99AfL26v2TTdRk2c5Qw3PW8/v2ON9BqfrHWRyyQ52MrX6h1QP5rEuMNeHawbBfjiWmrvc2YgfdtBA3bDuC5b3QaWhDi/kWUIKdTrhhlfV+chHiyLRuNhgfd+wgzFM2fTNKy0y7Xp7epD/uBPOIzOWj6rnG7XNV0a7cA+RPBOHxPQ/TKNyqJ1ZTmwFbgkaAQ49a2B6B6FG20BrbUBxgCjMdxH4GtOBCCOvk4HJyxYwl97S3hpahl260c67L53LE56zpbXU07rrSxveefYhY3lIE3UhQ8E="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe nomr --channel=main
