channels:
  targets:
  - [nomr, main]
travis:
  secure:
    BINSTAR_TOKEN: gvrKAaEairg2Q+Byzd3tgaj56cg2B87nnWXef3AF7TxLhiqhpt1LCLCUEYlDEtJDWjdLSRG+N73R2TQIGs1YKR7nk03JpUWnPu2DVGR/CgXBA9awL0bb+5Vu7NKYtlSv6r4iQw5pv8j8rceg6BkrqsuwMQwukHOZnvp265/A8/2Hsz37qx9t2yplW0gKK43JQR0AvW30A/VGc4t2WA+UMyeFRW5dC5lryhN8xcre+NJ5TwMOXiRw3TfLo/1vpOpBtoAoB7rwvN88YlFcm0m1IrMhNoFbuKNaQXUrWVL0lzGvyzF4SglXRvWHVBos8GDE0Ym5iUC19mtvWJ6t8y/ZIKvPSo6VNqhHbt6EFkywjG33IcXnfaGAltInDFIluwfpLgWI9o+kg/PD+Fm99AfL26v2TTdRk2c5Qw3PW8/v2ON9BqfrHWRyyQ52MrX6h1QP5rEuMNeHawbBfjiWmrvc2YgfdtBA3bDuC5b3QaWhDi/kWUIKdTrhhlfV+chHiyLRuNhgfd+wgzFM2fTNKy0y7Xp7epD/uBPOIzOWj6rnG7XNV0a7cA+RPBOHxPQ/TKNyqJ1ZTmwFbgkaAQ49a2B6B6FG20BrbUBxgCjMdxH4GtOBCCOvk4HJyxYwl97S3hpahl260c67L53LE56zpbXU07rrSxveefYhY3lIE3UhQ8E=
appveyor:
  secure:
    BINSTAR_TOKEN: iCSCYlUvHy+Dj6sGoT0mpXdKB5SeNBmJm6Q9e+ylBTg4FoemSUf2MFxsN2J1Y0u2
